service:
    name: worker-sandbox
    shutdown_timeout: 10s

logging:
    level: info
    add_source: false
    include_trace_id: true

tracing:
    enabled: true
    endpoint: alloy.lan:4317
    protocol: grpc
    insecure: false
    sample_ratio: 1.0

profiling:
    enabled: true
    server_address: https://pyroscope-ingest.lan
    namespace: worker-sandbox
    basic_auth_user: ""
    basic_auth_password: ""
    tenant_id: ""

nats:
    url: nats://nats.database.svc.cluster.local:4222
    username: example_user
    password: example_password
    queue_group_prefix: worker-sandbox
    subscribers_count: 1
    close_timeout: 30s
    ack_wait_timeout: 30s
    subscribe_timeout: 30s
    jetstream:
        enabled: true
        auto_provision: true
        track_msg_id: true
        ack_async: false
        durable_prefix: worker-sandbox

worker:
    topic: worker-sandbox.jobs
