name: Markdownlint

on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/markdownlint.yml"
            - ".markdownlint-cli2.*"
            - ".markdownlint.*"
            - "**/*.md"
            - "**/*.markdown"
    pull_request:
        paths:
            - ".github/workflows/markdownlint.yml"
            - ".markdownlint-cli2.*"
            - ".markdownlint.*"
            - "**/*.md"
            - "**/*.markdown"

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    markdownlint:
        name: Markdownlint
        runs-on: ubuntu-latest
        steps:
            # actions/checkout v6.0.2
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

            # DavidAnson/markdownlint-cli2-action v23.1.0
            - uses: DavidAnson/markdownlint-cli2-action@6b51ade7a9e4a75a7ad929842dd298a3804ebe8b
